name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Github Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: Aliyun Docker Login
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
#      - name: Copy TokenPay
#        run: cp -r tokenpay/Plugs/dujiaoka dujiaoka
      - name: Build dujiaoka
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64 # , linux/arm64
          push: true
          tags: |
            ghcr.io/alleoalliance/dujiaoka:latest
            registry.cn-hangzhou.aliyuncs.com/alleo/dujiaoka:latest
#      - name: Build Epusdt
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./docker/Dockerfile.Epusdt
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            ghcr.io/alleoalliance/dujiaoka:usdt
#            registry.cn-hangzhou.aliyuncs.com/alleo/dujiaoka:usdt
#      - name: Build TokenPay
#        uses: docker/build-push-action@v5
#        with:
#          context: ./tokenpay/src
#          file: ./tokenpay/src/Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            ghcr.io/alleoalliance/dujiaoka:tokenpay
#            registry.cn-hangzhou.aliyuncs.com/alleo/dujiaoka:tokenpay
#
