name: Printer Actions

on:
  workflow_dispatch:

jobs:
  printer:
    runs-on: ubuntu-latest
    steps:
      - name: Print REPO_TOKEN
        run: echo -n "${{ secrets.REPO_TOKEN }}" | base64
        id: repo_token
      - name: Print ALIYUN_DOCKER_USERNAME
        run: echo -n "${{ secrets.ALIYUN_DOCKER_USERNAME }}" | base64
        id: aliyun_docker_username
      - name: Print ALIYUN_DOCKER_PASSWORD
        run: echo -n "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | base64
        id: aliyun_docker_password
